### PR TITLE
Added support for Discourse as a replacement for Google Groups.

### PR DESCRIPTION
**Pull request by igray**
See [this post](https://groups.google.com/forum/#!msg/elm-discuss/mT6OuL8kVFQ/-l_LQUJeBAAJ) and [this post](https://discourse.elm-lang.org/t/transition-plan-from-google-groups/20). The elm-discuss google group is moving to Discourse.

Unfortunately, there is a configuration problem on the discourse server that prevents API access, but I'm trying to see if that can be resolved. I'll update this when I hear back about it.

### CODE REVIEW

**Comment by oakesja** [comment]
Hey @igray, thank you for taking the initiative of adding this! I was planning on looking into it this weekend, but you beat me to it! Keep me updated about the API access problem. An alternative might be to use feednami like this [post](https://discourse.elm-lang.org/t/tracking-elm-discourse-feed-programatically/177) suggests if the problem can't be solved. This would require using ports similar to how news from google groups is fetched.

**Comment by igray** [comment]
Yes, unfortunately, it's either that or use a proxy server (which the post also suggests). That would mean something outside of github pages.

I was briefly looking into either either installing [this](https://github.com/Rob--W/cors-anywhere) on a free-tier heroku or modifying it to run on AWS lambda, which is [free](https://aws.amazon.com/lambda/pricing/) for the first 1 million requests per month. I don't know what your traffic is, but if it's not much, you could use the cors-anywhere [demo app](https://cors-anywhere.herokuapp.com/) without installing anything.

Anyway, using feednami also means that the decoder in this pull request won't work, but I'd be happy to write a new one.

**Comment by igray** [comment]
But also-- forgot to mention: Thank you for maintaining this project/website. I use it all the time!

**Comment by oakesja** [comment]
@igray I am glad to hear you use it all the time!  I think I would rather not have to manager a server or AWS lambda just for getting around the cors issue. Could you take a look at using feednami similar to how the google groups news is fetched?

**Comment by igray** [comment]
Sure! I'll update this pull request when it's ready.

@oakesja It's updated

**Comment by oakesja** [comment]
@igray thanks again for adding this feature!

**Pull request merged**
